### ISSUE TITLE
Repo & build system setup

### ISSUE THREAD

**Issue by jakubfiala** [wellcometrust/together-science-can#1]
Tasks:
- [x] set up the npm package + dependencies
- [x] set up webpack + babel to bundle the front-end JS and SCSS
- [x] set up npm scripts

**Comment by alfraser86** [comment]
Split this into three:
1. Creating schema
2. Basic set up
3. Building the node app (This may end up being broken down more)

**Comment by jakubfiala** [comment]
@alfraser86 this is done:

> Creating schema - #24 
Basic set up - #1
Building the node app - #25

**Comment by jakubfiala** [comment]
closing as tasks have been completed
