### ISSUE TITLE
Hosting & DNS

### ISSUE THREAD

**Issue by jakubfiala** [wellcometrust/together-science-can#22]
We need to set up an S3 bucket with the correct permissions, make sure assets get loaded properly, get a domain and redirect it to the bucket on launch.

**Comment by alfraser86** [comment]
@wellingk Need to start thinking about environments, permissions, route 53. We will also need a certificate as it needs to be https.

**Comment by alfraser86** [comment]
Need to think about where the terraform will go.

**Comment by wellingk** [comment]
All done
