### ISSUE TITLE
Create a JSON schema for site content

### ISSUE THREAD

**Issue by jakubfiala** [wellcometrust/together-science-can#24]
this includes:

- the schema itself (could be used if we decide to make an editor)
- a dummy JSON file to use during dev, to which we'll later add final content and use in prod
- schema should be signed off by someone (@alfraser86 who?)

**Comment by alfraser86** [comment]
@jakubfiala schema should be thoroughly code reviewed and ran past people like @mildlydiverting who'll have helpful opinions.

**Comment by mildlydiverting** [comment]
may be helpful 
https://github.com/alphagov/govuk-content-schemas

**Comment by jakubfiala** [comment]
the schema is now created, will be updated along the way
