### ISSUE TITLE
Add domain in Route53 and get it pointed to the s3 bucket

### ISSUE THREAD

**Issue by alfraser86** [wellcometrust/together-science-can#26]

**Comment by wellingk** [comment]
Fine for Prod, and all set up ready to rock and roll.

Issue with Stage though!  Its is not possible without doing something super fancy to protect a  site hosted out of S3 with a username and password.  Investigated quite extensively and basically the options would warrant creating a seperate cluster which proxied traffic over to the S3 bucket.  Seemed complete overkill so will set up stage on CE server.

**Comment by jakubfiala** [comment]
the stage on CE server is now set up, can we close this @alfraser86 @wellingk ?

**Comment by jakubfiala** [comment]
nobody actually wanted to see the site on stage, so I guess we were ok without the CE build. Just need to get it pointed to the S3 bucket on D Day @wellingk

**Comment by wellingk** [comment]
All done and live
