### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by jakubfiala** [wellcometrust/together-science-can#4]
tasks:

- [ ] get copy/images for social media tags, Open Graph, mobile home screen logo, etc.
- [ ] add relevant `<meta>` tags
- [x] add RDF attributes to HTML where relevant (see http://schema.org/)
- [ ] check and/or debug using FB, Twitter etc. developer tools

**Comment by juliamgodinho** [comment]
@jakubfiala In case you start working on this before I come back, please send a message to either Jen S or Amy C.
