### ISSUE TITLE
Add poster to page

### ISSUE THREAD

**Issue by juliamgodinho** [wellcometrust/together-science-can#66]
Add this poster under "Create a poster" in the Ideas for Action section: [SP-6817.1_TSC_A3 downloadable poster_AW.PDF](https://github.com/wellcometrust/together-science-can/files/1321727/SP-6817.1_TSC_A3.downloadable.poster_AW.PDF)
![capture](https://user-images.githubusercontent.com/28559367/30703213-f4790190-9ee6-11e7-85d6-c8f5a5672151.JPG)

**Comment by jakubfiala** [comment]
closing this as done
